apiVersion: apps/v1
kind: Deployment
metadata:
  name: person-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: person-api-pod
  template:
    metadata:
      labels:
        app: person-api-pod
    spec:
      containers:
        - name: person-api-pod
          image: person-api:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: HTTP_PORT
              value: "8080"
            - name: MONGO_CONNECTION_URL
              value: ""
            - name: REDIS_CONNECTION_URL
              value: ""
            - name: NEW_RELIC_LICENCE
              value: ""
            - name: NEW_RELIC_ENABLED
              value: f
            - name: REDIS_PASS
              value: ""
            - name: IDEMPOTENCY_ENABLED
              value: t
            - name: SWAGGER_HOST
              value: ""
            - name: GIN_MODE
              value: "release"
          livenessProbe:
            httpGet:
              path: /v1/healthcheck
              port: http
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /v1/healthcheck
              port: http
            initialDelaySeconds: 5
          resources:
            limits:
              cpu: 150m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 80Mi